// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coderush.Data;

namespace coderush.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201018185204_InitialDb2")]
    partial class InitialDb2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("coderush.Models.ACR_PumpOnGround", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("ACR_PumpOnGround");
                });

            modelBuilder.Entity("coderush.Models.ACR_ShihlinCtrl", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("ACR_ShihlinCtrl");
                });

            modelBuilder.Entity("coderush.Models.ACR_SteamSterilizerMSTV", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("ACR_SteamSterilizerMSTV");
                });

            modelBuilder.Entity("coderush.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_Centrifuge", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_Centrifuge");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_Centrifuge5424", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_Centrifuge5424");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_DellDeskComp", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_DellDeskComp");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_FLUOstarOmega", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_FLUOstarOmega");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_HaierDW_40L508DeepFreezer", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_HaierDW_40L508DeepFreezer");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_HaierHYC", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_HaierHYC");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_HeatSealer", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_HeatSealer");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_KingFisherFlex", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_KingFisherFlex");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_LPVortexMixer", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_LPVortexMixer");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_MicroLabNIMBUS4", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_MicroLabNIMBUS4");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_NanoDropOne", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_NanoDropOne");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_NanoPhotometer", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_NanoPhotometer");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_PerkinElmerChemagic360", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_PerkinElmerChemagic360");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_PerkinElmerJanusG3", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_PerkinElmerJanusG3");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_QIAsymphonySP", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_QIAsymphonySP");
                });

            modelBuilder.Entity("coderush.Models.BSLDNAExt_Qubit4Fluorometer", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLDNAExt_Qubit4Fluorometer");
                });

            modelBuilder.Entity("coderush.Models.BSLSamMgmt_BioSafetyCabinet", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLSamMgmt_BioSafetyCabinet");
                });

            modelBuilder.Entity("coderush.Models.BSLSamMgmt_BradyPrinteri5100", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLSamMgmt_BradyPrinteri5100");
                });

            modelBuilder.Entity("coderush.Models.BSLSamMgmt_CenceCentrifugeCL5R", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLSamMgmt_CenceCentrifugeCL5R");
                });

            modelBuilder.Entity("coderush.Models.BSLSamMgmt_Centrifuge", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLSamMgmt_Centrifuge");
                });

            modelBuilder.Entity("coderush.Models.BSLSamMgmt_Centrifuge5702", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLSamMgmt_Centrifuge5702");
                });

            modelBuilder.Entity("coderush.Models.BSLSamMgmt_DellDeskComp", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLSamMgmt_DellDeskComp");
                });

            modelBuilder.Entity("coderush.Models.BSLSamMgmt_ESCOClassIITypeA2", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLSamMgmt_ESCOClassIITypeA2");
                });

            modelBuilder.Entity("coderush.Models.BSLSamMgmt_LPVortexMixer", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLSamMgmt_LPVortexMixer");
                });

            modelBuilder.Entity("coderush.Models.BSLSamMgmt_MicroLabSTARlet", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLSamMgmt_MicroLabSTARlet");
                });

            modelBuilder.Entity("coderush.Models.BSLSamMgmt_MultitubeVortexer", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLSamMgmt_MultitubeVortexer");
                });

            modelBuilder.Entity("coderush.Models.BSLSamMgmt_Refrigerator", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLSamMgmt_Refrigerator");
                });

            modelBuilder.Entity("coderush.Models.BSLSamMgmt_STPlusSeriesCentrifuge", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLSamMgmt_STPlusSeriesCentrifuge");
                });

            modelBuilder.Entity("coderush.Models.BSLSamMgmt_TheromoMixer", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("BSLSamMgmt_TheromoMixer");
                });

            modelBuilder.Entity("coderush.Models.CP1_DellDeskComp", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("CP1_DellDeskComp");
                });

            modelBuilder.Entity("coderush.Models.CP1_ThermoFisher80", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("CP1_ThermoFisher80");
                });

            modelBuilder.Entity("coderush.Models.Condition", b =>
                {
                    b.Property<int>("Condition_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Condition_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Condition_id");

                    b.ToTable("Condition");
                });

            modelBuilder.Entity("coderush.Models.ConsumablesAndLabware", b =>
                {
                    b.Property<int>("CL_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CL_expiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CL_layerCompartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CL_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CL_partNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CL_qtyOnhand")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CL_statusDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CL_storageTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Condition_id")
                        .HasColumnType("int");

                    b.Property<int>("Location_id")
                        .HasColumnType("int");

                    b.Property<int>("Status_id")
                        .HasColumnType("int");

                    b.Property<int>("Storage_id")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfMeasure_id")
                        .HasColumnType("int");

                    b.HasKey("CL_id");

                    b.ToTable("ConsumablesAndLabware");
                });

            modelBuilder.Entity("coderush.Models.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("coderush.Models.ILLUMINALibConst_Others", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("ILLUMINALibConst_Others");
                });

            modelBuilder.Entity("coderush.Models.ILLUMINASeqLab_NovaSeq6000", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("ILLUMINASeqLab_NovaSeq6000");
                });

            modelBuilder.Entity("coderush.Models.ILLUMINASeqLab_Others", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("ILLUMINASeqLab_Others");
                });

            modelBuilder.Entity("coderush.Models.Instruments", b =>
                {
                    b.Property<int>("Instru_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Instru_assetValue")
                        .HasColumnType("float");

                    b.Property<double>("Instru_averageCost")
                        .HasColumnType("float");

                    b.Property<string>("Instru_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instru_partNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Instru_qtyOnhand")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Instru_serialNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("Instru_warrEnddate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Instru_warrStartdate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Location_id")
                        .HasColumnType("int");

                    b.Property<int>("Sections_id")
                        .HasColumnType("int");

                    b.Property<int>("Suppliers_id")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfMeasure_id")
                        .HasColumnType("int");

                    b.HasKey("Instru_id");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("coderush.Models.KitsAndReagents", b =>
                {
                    b.Property<int>("KR_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("KR_assetValue")
                        .HasColumnType("float");

                    b.Property<double>("KR_averageCost")
                        .HasColumnType("float");

                    b.Property<string>("KR_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("KR_expiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("KR_partNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KR_qtyOnhand")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Location_id")
                        .HasColumnType("int");

                    b.Property<int>("Sections_id")
                        .HasColumnType("int");

                    b.Property<int>("Suppliers_id")
                        .HasColumnType("int");

                    b.Property<int>("UnitOfMeasure_id")
                        .HasColumnType("int");

                    b.HasKey("KR_id");

                    b.ToTable("KitsAndReagents");
                });

            modelBuilder.Entity("coderush.Models.Lab1_DellDeskComp", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("Lab1_DellDeskComp");
                });

            modelBuilder.Entity("coderush.Models.Lab1_Others", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("Lab1_Others");
                });

            modelBuilder.Entity("coderush.Models.Lab2_DellDeskComp", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("Lab2_DellDeskComp");
                });

            modelBuilder.Entity("coderush.Models.Lab2_Others", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("Lab2_Others");
                });

            modelBuilder.Entity("coderush.Models.Lab3_DellDeskComp", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("Lab3_DellDeskComp");
                });

            modelBuilder.Entity("coderush.Models.Lab3_Others", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("Lab3_Others");
                });

            modelBuilder.Entity("coderush.Models.Lab4_DellDeskComp", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("Lab4_DellDeskComp");
                });

            modelBuilder.Entity("coderush.Models.Lab4_Others", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("Lab4_Others");
                });

            modelBuilder.Entity("coderush.Models.Location", b =>
                {
                    b.Property<int>("Location_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Location_id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("coderush.Models.Sections", b =>
                {
                    b.Property<int>("Sections_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Sections_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sections_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sections_id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("coderush.Models.Status", b =>
                {
                    b.Property<int>("Status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Status_id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("coderush.Models.Storage", b =>
                {
                    b.Property<int>("Storage_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Storage_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Storage_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Storage_id");

                    b.ToTable("Storage");
                });

            modelBuilder.Entity("coderush.Models.Suppliers", b =>
                {
                    b.Property<int>("Suppliers_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Suppliers_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suppliers_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Suppliers_id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("coderush.Models.UnitOfMeasure", b =>
                {
                    b.Property<int>("UnitOfMeasure_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UnitOfMeasure_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasure_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitOfMeasure_id");

                    b.ToTable("UnitOfMeasure");
                });

            modelBuilder.Entity("coderush.Models.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserProfileId");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("coderush.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("coderush.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("coderush.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("coderush.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
